sudo: false

language: php

php:
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm

env:
    global:
        secure: QcFQQ/vlOLZk7IEetzGl8IuyFkeMzaVI/jDGcwHKP4xNoRP/gNbYsXEKBnwqgMW6EKf88mie0XzALeDK6mck2OAdBJoVw0cG5N07joBMQ+yBsRiLFqgQN8FwwHeQqBK8yUUL/CNbUbRZNPAobCVS7MPuo/gUcMofgbS+cq9TWUfvJw0DyC3Fq97FQblvdN2LURyfOp78+65MKafBkZ3yePAV+I3s7c9HUJPeYEOotcVjsk0Xi+JdvlHvZ59c7D0wZ/Sc/X9Fpxr23fda3KoYvCIWtIdpJ+g+WHOv7+eN10elROKyTcprCs4pNVswHwRyvx6GHoClNUP5Cns150d83+S9yyT8gV1MW+iFufTXLO0rp4GMRi5/Axd1I52qVGvpQE0lIdY2o1IS2ayOdXFhOW7VfCmL7923xZnc1cUvVxymqy5IoTO70h4rUMrPtTw+Q5tZb2y9aNXt9eVXV8mPRLdK+2zL7P8+lVqffN+wfheKwT++2ku96JnB5HihADbJ1MsgwgN/xjfOe5OpoorQrzdYk3tAq/W/daW7P1tfegX70oJA5xl94wJ1ygV0iMN6pDaWU+HMv2nHVgI/lw1WZGAlCXu5C3vsz9gM7SpAHRMDmT9cRpJtxxfOc+4ToGzwjpJyyuIojuO5rYpUp4wLa5uP8qV0tXj3R+8z69AZr1g=

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

cache:
    directories:
        - node_modules
        - $HOME/.composer/cache/files

before_install:
    - rm -rf "$HOME/.nvm"
    - git clone https://github.com/creationix/nvm.git "$HOME/.nvm"
    - source "$HOME/.nvm/nvm.sh"
    - nvm install node
    - npm config set progress false
    - npm install -g npm
    - |
        if [ "$TRAVIS_PULL_REQUEST" = "true" ]; then
            phpenv config-rm xdebug.ini
        fi
    - composer self-update
    - composer global require --prefer-source --no-interaction hirak/prestissimo

install:
    - npm install
    - composer install --prefer-source --no-interaction

script:
    - npm run-script lint-ci
    - composer test-ci

after_success:
    - |
        if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
            vendor/bin/coveralls --verbose
        fi
    - |
        if [ "$TRAVIS_PHP_VERSION" = '5.6' ] && [ "$TRAVIS_PULL_REQUEST" = 'false' ]; then
            if [ "$TRAVIS_BRANCH" = 'master' ] || [ -n "$TRAVIS_TAG" ]; then
                BUILD_PATH="$(pwd)"
                REPOSITORY=${REPOSITORY:-"https://${GH_TOKEN}@github.com/$TRAVIS_REPO_SLUG.git"}
                BRANCH=${BRANCH:-"gh-pages"}
                TAG="$TRAVIS_TAG-gh-pages"
                TAG_MESSAGE=$(echo "$TRAVIS_TAG" | sed -e "s/v\([0-9]\+\(.[0-9]\+\)*\)/\1-gh-pages/")
                APIGEN_BUILD_PATH=${APIGEN_BUILD_PATH:-"/tmp/apigen"}
                GIT_AUTHOR_NAME=${GIT_AUTHOR_NAME:-"Travis CI"}
                GIT_AUTHOR_EMAIL=${GIT_AUTHOR_EMAIL:-"travis@travis-ci.org"}
                git clone --quiet --branch "$BRANCH" --depth 1 "$REPOSITORY" "$APIGEN_BUILD_PATH" > /dev/null 2>&1
                yes | vendor/bin/apigen generate -d "$APIGEN_BUILD_PATH"
                cd "$APIGEN_BUILD_PATH" || exit 1
                git config user.name "$GIT_AUTHOR_NAME"
                git config user.email "$GIT_AUTHOR_EMAIL"
                git add -A
                git commit -m 'docs: generate API documentation'
                if [ -n "$TRAVIS_TAG" ]; then git tag -a "$TAG" -m "$TAG_MESSAGE"; fi
                git push --quiet --follow-tags origin "$BRANCH" > /dev/null 2>&1
                cd "$BUILD_PATH"
            fi
        fi

notifications:
    email: false

    slack:
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
        rooms:
            - secure: wLBtpxk5UROvs4ZHXiVDs3ppZnW9Hh8izjbhSTneZ+YqCZjIVFTi9ynzExG+Aqnp+2uCUPgt1SY7dp0HkiY6E94PypNAM+DInHpEZefXAgIqawGjH0br2Py5R4ZnSGpYV7nRCPgv9/qO/gLCrNHOKS/97KIpU/2Zt7Md+ukqVuXzUzlXrZxZgNlPGmx7DCeFO6CK7hMLyB8i4anxVlqBiqWCAVYh020MdrrhUnQFx6bCwxWtvXFzNzLKEpnrzhJfp4GhbIBr3no3G4I9i8v2VllkXb8vo4x2heXuLnjQGH8nCKxSM0Ms+ScxSOgupcgD6Z4MMgtpK0Bri/p/RhTPJfSyBbP+6G7xt/heF/bEvaVwkwgepmSaRZFx+L3sbyDAjnf4kCONLJr0ffgzRqR8IEw7yCJzC1MDCPPgBaqW018in4w7fLpeMQtzdUsGcNXBk9kE8B022yWP8N8/9xMR5t9NOp45jnOkbMqmm+I4PUTLBPb/v7nlg8bNdlJKFQBdgW0b4/D1R42mSQfLQPCnmNKaoYLqlfNDsxWRrZ8Xp2rg6WRRVXIH+ZrFyK1JX42cG91v8SeoPw2iip5QgSlWXCCEoWPvgN4e/9pDPIHa2Il0mSpy8o1oafPrihu+QfMS+agOTbFyUxfh6cjnqvICxh3cPQD9v5epMliSnTIL658=
