sudo: false

language: php

php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer install --prefer-source

script:
  - composer test-ci

notifications:
  email:
    on_success: never
    on_failure: change
